apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world.fullname" . }}-2
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}-2
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{.Values.containerPort}}
      protocol: TCP
      name: http
  selector:
    {{- include "hello-world.selectorLabels" . | nindent 4 }}-2
